server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amachiop/configservice
          default-label: master
          search-paths:
          - '*.yaml'